version: 0.2
env:
  variables:
    SLS_STAGE: "Prod"
  secrets-manager:
    # Databse
    DB_NAME: oauth
    DB_HOST: prod/busarm:db_host
    DB_PORT: prod/busarm:db_port
    DB_USER: prod/busarm:db_username
    DB_PASS: prod/busarm:db_password
install:
    runtime-versions:
        docker: 18
        php: 8.0
phases:
    build:
        commands:
            - echo Build started on `date`
            
            - echo Installing composer..
            - composer install --no-dev

    post_build:
        commands:
            - echo Build completed on `date`

            - echo Migrate DB
            - composer migration:migrate

            - echo Deploying serverless
            - sls deploy --stage=$SLS_STAGE --region=$AWS_REGION --verbose --param="APP_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION" --param="APP_DEPLOY_DATE=$CODEBUILD_START_TIME"

cache:
    paths:
        - "vendor/**/*"
