version: '3.7'

networks:
  backend:
    name: wecari
    external: true

services:

  # Web server
  oauth:
    image: webdevops/php-nginx:8.0-alpine
    volumes:
      - .:/var/www:rw
      - ./nginx/app.conf:/opt/docker/etc/nginx/conf.d/app.conf
    ports: 
      - 8000:80
    environment:
        WEB_DOCUMENT_ROOT: '/var/www/public'
        WEB_DOCUMENT_INDEX: index.php
        WEB_ALIAS_DOMAIN: 'oauth.test'
        # APP
        APP_NAME: 'Wecari Oauth'
        COMPANY_NAME: 'Wecari'
        ENV: local
        ENCRYPTION_KEY: "P6xpRQ#MWxP6MNdDs2#g*eQzuDHx?rN"
        # Custom Paths
        APP_CACHE_PATH: '/tmp/cache'
        APP_UPLOAD_PATH: '/tmp/uploads'
        APP_LOGS_PATH: '/tmp/logs'
        # Dev DB Credentials
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USER: root
        DB_PASS: root
    networks: 
      - backend