version: '3.7'

networks:
  backend:
    name: wecari
    external: true

volumes:
  app:
    driver: local

services:

  # Web server
  oauth:
    image: webdevops/php-nginx:7.4-alpine
    volumes:
      - .:/var/www:rw
      - ./nginx/app.conf:/opt/docker/etc/nginx/conf.d/app.conf
    ports: 
      - 8000:80
    environment:
        WEB_DOCUMENT_ROOT: '/var/www'
        WEB_DOCUMENT_INDEX: index.php
        WEB_ALIAS_DOMAIN: 'oauth.test'
        APP_NAME: 'Wecari Oauth'
        COMPANY_NAME: 'Wecari'
        ENV: development # Environment variable 
        ENCRYPTION_KEY: "P6xpRQ#MWxP6MNdDs2#g*eQzuDHx?rN"
        # Custom Paths
        APP_CACHE_PATH: '/tmp/cache'
        APP_UPLOAD_PATH: '/tmp/uploads'
        APP_LOGS_PATH: '/tmp/logs'
    networks: 
      - backend