# TODO
# -------
# Decrease heatbeat rate to 10 minutes for production

service: Wecari-Oauth

provider:
    name: aws
    runtime: provided
    profile: wecari
    region: ${opt:region, 'eu-west-2'} # e.g serverless delopy --region eu-west-2 (default = 'eu-west-2')
    stage: ${opt:stage, 'Dev'} # e.g serverless delopy --stage dev (default = 'dev')
    stackName: Wecari-Oauth-${self:provider.stage}
    apiName: Wecari-Oauth-${self:provider.stage}
    role: ${self:custom.roleName}
    environment: # define service wide environment variables here
        ENV: ${self:provider.stage} # Environment variable
        BREF_BINARY_RESPONSES: 1 # For bref to return binary responses. Bref will automatically encode responses to base64
        # AWS RDS - Production
        DB_NAME: 13243546576879_oauth
        DB_HOST: ${self:custom.dbSecret.host}
        DB_PORT: ${self:custom.dbSecret.port}
        DB_USER: ${self:custom.dbSecret.username}
        DB_PASS: ${self:custom.dbSecret.password}
        # AWS RDS - Staging
        STAGE_DB_HOST: ${self:custom.dbSecret.host}
        STAGE_DB_PORT: ${self:custom.dbSecret.port}
        STAGE_DB_USER: ${self:custom.dbSecret.username}
        STAGE_DB_PASS: ${self:custom.dbSecret.password}
        # AWS SMTP
        AWS_SMTP_HOST: ${self:custom.smtpSecret.host}
        AWS_SMTP_PORT: ${self:custom.smtpSecret.port}
        AWS_SMTP_KEY: ${self:custom.smtpSecret.username}
        AWS_SMTP_SECRET: ${self:custom.smtpSecret.password}
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    vpc:
        securityGroupIds:
            - sg-eaba578b
        subnetIds:
            - subnet-6c499c20
            - subnet-a9880ed3
            - subnet-e453298d

plugins:
    - ./vendor/bref/bref

package:
    exclude:
        - composer.json 
        - composer.lock
        - .git/**
        - .serverless/**
        - .htaccess
       
functions:
    Authorize:
        handler: index.php
        description: 'Allow user to authorize access to their account'
        memorySize: 128
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http:  
                path: '/authorize/{any+}'
                method: ANY
                cors:         
                    origin: '*'
                    headers: ${self:custom.corsHeaders} 
                    allowCredentials: false
                    cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate' 
            - schedule:
                rate: rate(10 minutes)
                input:
                    warmer: true
                    
    Resources:
        handler: index.php
        description: 'Retrieve oauth resources e.g user details with client credentials and access token'
        memorySize: 128
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http:  
                path: '/resources/{any+}'
                method: ANY
                cors:         
                    origin: '*'
                    headers: ${self:custom.corsHeaders} 
                    allowCredentials: false
                    cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate' 
            - schedule:
                rate: rate(10 minutes)
                input:
                    warmer: true
                    
    Token:
        handler: index.php
        description: 'Generate and verify oauth access tokens'
        memorySize: 256
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http:  
                path: '/token/{any+}'
                method: ANY
                cors:         
                    origin: '*'
                    headers: ${self:custom.corsHeaders} 
                    allowCredentials: false
                    cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate' 
            - schedule:
                rate: rate(10 minutes)
                input:
                    warmer: true

custom:
    dbSecret: ${ssm:/aws/reference/secretsmanager/prod/wecari/db~true}
    smtpSecret: ${ssm:/aws/reference/secretsmanager/prod/wecari/smtp~true}
    roleName: WecariOauthLambdaRole${self:provider.stage}
    corsHeaders: 
      - Content-Type
      - Authorization
      - Access-Token
      - X-Requested-With
      - X-Api-Key
      - X-Access-Token
      - X-Amz-Date
      - X-Amz-User-Agent
      
 
resources:
  Resources: 
    WecariOauthLambdaRoleDev:
      Type: AWS::IAM::Role
      Properties:
        RoleName: WecariOauthLambdaRoleDev
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: WecariAPILambdaPolicyDev
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - ec2:CreateNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DescribeSecurityGroups
                    - ec2:DescribeSubnets
                    - ec2:DescribeVpcs
                  Resource: "*" 
          
    WecariOauthLambdaRoleProd:
      Type: AWS::IAM::Role
      Properties:
        RoleName: WecariOauthLambdaRoleProd
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: WecariAPILambdaPolicyProd
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - ec2:CreateNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DescribeSecurityGroups
                    - ec2:DescribeSubnets
                    - ec2:DescribeVpcs
                  Resource: "*" 
          
  Outputs:
    RoleName:
      Value: ${self:custom.roleName}
      Description: Name of the created Amazon Role.