service: Busarm-Oauth
frameworkVersion: ^3.21.0

provider:
    name: aws
    ecr:
        scanOnPush: true
        images:
            busarm-oauth:
                path: ./
                file: Dockerfile.sls
            busarm-oauth-console:
                path: ./
                file: Dockerfile.console.sls
    runtime: provided.al2
    region: ${opt:region, ''}
    stage: ${opt:stage, ''}
    stackName: Busarm-Oauth-${self:provider.stage}
    apiName: Busarm-Oauth-${self:provider.stage}
    role: ${self:custom.roleName}
    logRetentionInDays: ${self:custom.logRetentionInDays}
    deploymentMethod: direct
    environment: # define service wide environment variables here
        ENV: ${self:provider.stage} # Environment variable
        BREF_BINARY_RESPONSES: "1" # For bref to return binary responses. Bref will automatically encode responses to base64
        SEPARATE_VENDOR: "0"
        # App
        APP_VERSION: ${param:APP_VERSION}
        APP_DEPLOY_DATE: ${param:APP_DEPLOY_DATE}
        APP_NAME: "Busarm Oauth"
        APP_THEME_PRIMARY_COLOR: "#267272"
        APP_THEME_SECONDARY_COLOR: "#e9ffb7"
        COMPANY_NAME: "Busarm"
        ENCRYPTION_KEY: ${self:custom.secret.${self:provider.stage}.oauth_encryption_key}
        BUGSNAG_KEY: ${self:custom.secret.${self:provider.stage}.oauth_bugsnag_key}
        EMAIL_INFO: "info@busarm.com"
        EMAIL_SUPPORT: "support@busarm.com"
        SYSTEM_SHUT_DOWN_TIME: ${self:custom.stopTime.${self:provider.stage}}
        SYSTEM_START_UP_TIME: ${self:custom.startTime.${self:provider.stage}}
        MAINTENANCE_MODE: "0"
        API_URL: ${self:custom.apiUrl.${self:provider.stage}}
        APP_URL: ${self:custom.appUrl.${self:provider.stage}}
        ASSET_URL: ${self:custom.assetUrl.${self:provider.stage}}
        PARTNER_URL: ${self:custom.partnerUrl.${self:provider.stage}}
        # Databse
        DB_NAME: oauth
        DB_HOST: ${self:custom.secret.${self:provider.stage}.db_host}
        DB_PORT: ${self:custom.secret.${self:provider.stage}.db_port}
        DB_USER: ${self:custom.secret.${self:provider.stage}.db_username}
        DB_PASS: ${self:custom.secret.${self:provider.stage}.db_password}
        # SMTP
        SMTP_HOST: ${self:custom.secret.${self:provider.stage}.smtp_host}
        SMTP_PORT: ${self:custom.secret.${self:provider.stage}.smtp_port}
        SMTP_KEY: ${self:custom.secret.${self:provider.stage}.smtp_username}
        SMTP_SECRET: ${self:custom.secret.${self:provider.stage}.smtp_password}
        # Google
        RECAPTCHA_SECRET_KEY: ${self:custom.secret.${self:provider.stage}.recaptcha_secret_key}
        RECAPTCHA_CLIENT_KEY: ${self:custom.secret.${self:provider.stage}.recaptcha_client_key}
    apiGateway:
        binaryMediaTypes:
            - "*/*"
    vpc:
        securityGroupIds:
            - sg-01779fc0d4ec8930e
        subnetIds:
            - subnet-0b3cb32233833f746
            - subnet-07ca1983b3b5c7b68

plugins:
    - ./vendor/bref/bref
    - serverless-plugin-log-retention
    - serverless-plugin-canary-deployments
    - serverless-prune-plugin
package:
    exclude:
        - composer.lock
        - .env
        - .env.*
        - .git/**
        - .vscode/**
        - .serverless/**
        - .uploads/**
        - .cache/**
        - .logs/**
        - .htaccess
        - node_modules/**

params:
    Prod:
        APP_VERSION: "build-prod-1"
        APP_DEPLOY_DATE: ""
    Dev:
        APP_VERSION: "build-dev-1"
        APP_DEPLOY_DATE: ""

custom:
    bref:
        separateVendor: 0
    maxMem:
        Dev: 2048
        Prod: 4096
    superMem:
        Dev: 1024
        Prod: 2048
    highMem:
        Dev: 512
        Prod: 1024
    avgMem:
        Dev: 256
        Prod: 512
    lowMem:
        Dev: 128
        Prod: 256
    logRetentionInDays: 30
    secret:
        Dev: ${ssm:/aws/reference/secretsmanager/dev/busarm}
        Prod: ${ssm:/aws/reference/secretsmanager/prod/busarm}
    roleName: BusarmOauthLambdaRole
    # Urls
    apiUrl:
        Dev: "https://api.staging.busarm.com"
        Prod: "https://api.busarm.com"
    appUrl:
        Dev: "https://staging.busarm.com"
        Prod: "https://busarm.com"
    assetUrl:
        Dev: "https://cdn.staging.busarm.com"
        Prod: "https://cdn.busarm.com"
    partnerUrl:
        Dev: "https://partner.staging.busarm.com"
        Prod: "https://partner.busarm.com"
    startTime:
        Dev: "00:00" # Default 08:00 UTC
        Prod: ""
    stopTime:
        Dev: "14:00" # Default 22:00 UTC
        Prod: ""
    # Trafic shifting Deployment
    deploymentSettings:
        stages:
            - Prod # Only use blue/green deployment for production
    # Previous version prunning
    prune:
        automatic: true
        includeLayers: true
        number: 3 # Max versions allowed
functions:
    # Console
    Console:
        image:
            name: busarm-oauth-console
        description: "Busarm Console & Cron Job Scheduler"
        memorySize: ${self:custom.avgMem.${self:provider.stage}}
        timeout: 28
        package:
            exclude:
                - "public/**"
        deploymentSettings:
            type: AllAtOnce
            alias: Live

    Authorize:
        image:
            name: busarm-oauth
        description: "Allow user to authorize access to their account"
        memorySize: ${self:custom.avgMem.${self:provider.stage}}
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - http:
                  path: "/authorize/{any+}"
                  method: ANY
        deploymentSettings:
            type: AllAtOnce
            alias: Live

    Resources:
        image:
            name: busarm-oauth
        description: "Retrieve oauth resources e.g user details with client credentials and access token"
        memorySize: ${self:custom.highMem.${self:provider.stage}}
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - http:
                  path: "/resources/{any+}"
                  method: ANY
            - schedule:
                  rate: rate(5 minutes)
                  input:
                      warmer: true
        deploymentSettings:
            type: AllAtOnce
            alias: Live

    Token:
        image:
            name: busarm-oauth
        description: "Generate and manage oauth access tokens"
        memorySize: ${self:custom.highMem.${self:provider.stage}}
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - http:
                  path: "/token/{any+}"
                  method: ANY
            - schedule:
                  rate: rate(5 minutes)
                  input:
                      warmer: true
        deploymentSettings:
            type: AllAtOnce
            alias: Live

    Misc:
        image:
            name: busarm-oauth
        description: "Perform Miscellaneous tasks"
        memorySize: ${self:custom.avgMem.${self:provider.stage}}
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - http:
                  path: "/misc/{any+}"
                  method: ANY
        deploymentSettings:
            type: AllAtOnce
            alias: Live

resources:
    Resources:
        BusarmOauthLambdaRole:
            Type: AWS::IAM::Role
            Properties:
                RoleName: BusarmOauthLambdaRole${self:provider.stage}-${self:provider.region}
                Path: /
                AssumeRolePolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Principal:
                              Service:
                                  - lambda.amazonaws.com
                          Action: sts:AssumeRole
                Policies:
                    - PolicyName: BusarmOauthLambdaPolicy${self:provider.stage}
                      PolicyDocument:
                          Version: "2012-10-17"
                          Statement:
                              - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                                Action:
                                    - logs:CreateLogGroup
                                    - logs:CreateLogStream
                                    - logs:PutLogEvents
                                    - ec2:CreateNetworkInterface
                                    - ec2:DeleteNetworkInterface
                                    - ec2:DescribeNetworkInterfaces
                                    - ec2:DescribeSecurityGroups
                                    - ec2:DescribeSubnets
                                    - ec2:DescribeVpcs
                                Resource: "*"

    Outputs:
        RoleName:
            Value: ${self:custom.roleName}
            Description: Name of the created Amazon Role.
